language: php
php: 5.5
branches:
  only:
    - production
addons:
    ssh_known_hosts: ftp.cluster020.hosting.ovh.net
script: true
after_success:
  - sudo apt-get update
  - sudo apt-get install lftp
  - lftp sftp://${SFTP_USER}:${SFTP_PASSWORD}@ftp.cluster020.hosting.ovh.net -e "cd donate; mirror -R --exclude .git/ --exclude .travis.yml --exclude .directory --exclude .gitignore --exclude .idea/ --exclude README.md --exclude LICENSE; bye"

