language: php
php: 5.5
branches:
  only:
    - production
addons:
    ssh_known_hosts: ftp.cluster020.hosting.ovh.net
script: true
after_success:
  - sudo apt-get update
  - sudo apt-get install sshpass
  - find . -type d \( -path "./.*" \) -prune -o -type f \( -name "*" ! -name ".travis.yml" ! -name ".gitignore" ! -name "LICENCE" \) -printf '%P' -exec sshpass -p${SFTP_PASSWORD} sftp -oBatchMode=no -b - ${SFTP_USER}@ftp.cluster020.hosting.ovh.net:/home/poliedrobp/donate/ <<< $'put {}' \;

