language: php
php: 5.5
branches:
  only:
    - production
addons:
    ssh_known_hosts: ftp.cluster020.hosting.ovh.net
script: true
after_success:
  - sudo apt-get update
  - sudo apt-get install git-ftp
  - git ftp init -u ${SFTP_USER} -p ${SFTP_PASSWORD} "sftp://ftp.cluster020.hosting.ovh.net/home/poliedrobp/donate/"
